apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/maheshgowdamg/argocd.git
    targetRevision: master
    path: mongodb
    helm:
      values: |
        mongodb:
          
          global:
            storageClass: hostpath
          architecture: replicaset
          replicaCount: 3
          replicaSetName: rs0
          useStatefulSet: true
          auth:
            enabled: true
            existingSecret: mongo
          arbiter:
            enabled: false
          metrics:
            enabled: true
            resources:
              requests:
                memory: 100Mi
              limits:
                memory: 200Mi
          persistence:
            size: 4Gi
          resourcesPreset: xlarge
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

