apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.5.23    # <-- Use a valid chart version from Bitnami
    chart: postgresql
    helm:
      values: |
        architecture: replication

        global:
          postgresql:
            auth:
              existingSecret: postgresql
              database: postgres
          storageClass: hostpath

        metrics:
          enabled: true

        primary:
          extendedConfiguration: |
            max_connections = 3001
            shared_preload_libraries = 'pg_stat_statements'
            pg_stat_statements.track = all
            log_destination = 'stderr'
            logging_collector = on
            log_directory = '/bitnami/postgresql/logs'
            log_filename = 'postgresql.log'
            log_connections = off
            log_disconnections = off
            log_min_duration_statement = 1000
            log_statement = 'all'
          persistence:
            size: 2Gi
          resourcesPreset: medium

        readReplicas:
          replicaCount: 3
          extendedConfiguration: |
            max_connections = 3001
            shared_preload_libraries = 'pg_stat_statements'
            pg_stat_statements.track = all
            log_destination = 'stderr'
            logging_collector = on
            log_directory = '/bitnami/postgresql/logs'
            log_filename = 'postgresql.log'
            log_connections = off
            log_disconnections = off
            log_min_duration_statement = 1000
            log_statement = 'all'
          persistence:
            size: 2Gi
          resourcesPreset: medium

        replication:
          enabled: true
          numSynchronousReplicas: 1
          synchronousCommit: "on"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
